export const WEBHOOK_EVENT_CATEGORIES = {
  ASSINATURAS: [
    "subscription.created",
    "subscription.renewed",
    "subscription.canceled",
    "subscription.upgraded",
    "subscription.downgraded",
    "subscription.payment_failed",
  ],
  "ASSINATURAS POR PLANO": [
    "subscription.plus.created",
    "subscription.premium.created",
    "subscription.ministry_10.created",
    "subscription.ministry_20.created",
    "subscription.ministry_40.created",
    "subscription.plus.canceled",
    "subscription.premium.canceled",
    "subscription.ministry.canceled",
  ],
  CHECKOUT: [
    "checkout.started",
    "checkout.abandoned",
    "checkout.completed",
    "checkout.plus.started",
    "checkout.premium.started",
    "checkout.plus.abandoned",
    "checkout.premium.abandoned",
    "checkout.plus.completed",
    "checkout.premium.completed",
  ],
  PAGAMENTOS: ["payment.approved", "payment.refunded", "payment.chargeback"],
  USUÁRIOS: ["user.created", "user.login", "user.password_reset", "user.migrated", "user.email_confirmed"],
  PLANOS: [
    "plan.free_activated",
    "plan.plus_activated",
    "plan.premium_activated",
    "plan.ministry_activated",
  ],
  PLATAFORMA: ["repertoire.submitted", "repertoire.updated", "kit.downloaded", "playlist.created", "playlist.updated", "favorite.added"],
} as const;

export const WEBHOOK_EVENT_LABELS: Record<string, string> = {
  "subscription.created": "Assinatura iniciada",
  "subscription.renewed": "Assinatura renovada",
  "subscription.canceled": "Assinatura cancelada",
  "subscription.upgraded": "Upgrade de assinatura",
  "subscription.downgraded": "Downgrade de assinatura",
  "subscription.payment_failed": "Falha de pagamento da assinatura",
  "subscription.plus.created": "Plus iniciado",
  "subscription.premium.created": "Premium iniciado",
  "subscription.ministry_10.created": "Ministerial 10 iniciado",
  "subscription.ministry_20.created": "Ministerial 20 iniciado",
  "subscription.ministry_40.created": "Ministerial 40 iniciado",
  "subscription.plus.canceled": "Plus cancelado",
  "subscription.premium.canceled": "Premium cancelado",
  "subscription.ministry.canceled": "Ministerial cancelado",
  "checkout.started": "Checkout iniciado",
  "checkout.abandoned": "Checkout abandonado",
  "checkout.completed": "Checkout concluído",
  "checkout.plus.started": "Checkout Plus iniciado",
  "checkout.premium.started": "Checkout Premium iniciado",
  "checkout.plus.abandoned": "Checkout Plus abandonado",
  "checkout.premium.abandoned": "Checkout Premium abandonado",
  "checkout.plus.completed": "Checkout Plus concluído",
  "checkout.premium.completed": "Checkout Premium concluído",
  "payment.approved": "Pagamento aprovado",
  "payment.refunded": "Pagamento estornado",
  "payment.chargeback": "Pagamento contestado",
  "user.created": "Usuário criado",
  "user.login": "Login realizado",
  "user.password_reset": "Senha redefinida",
  "user.migrated": "Usuário migrado",
  "user.email_confirmed": "E-mail confirmado",
  "plan.free_activated": "Plano Free ativado",
  "plan.plus_activated": "Plano Plus ativado",
  "plan.premium_activated": "Plano Premium ativado",
  "plan.ministry_activated": "Plano Ministerial ativado",
  "repertoire.submitted": "Repertório enviado",
  "repertoire.updated": "Repertório atualizado",
  "kit.downloaded": "Download de kit",
  "playlist.created": "Playlist criada",
  "playlist.updated": "Playlist atualizada",
  "favorite.added": "Favorito adicionado",
};

export const WEBHOOK_EVENTS = Object.values(WEBHOOK_EVENT_CATEGORIES).flat() as readonly string[];
export type WebhookEvent = (typeof WEBHOOK_EVENTS)[number];
