export const WEBHOOK_EVENT_CATEGORIES = {
  "CADASTRO E ACESSO": [
    "user.created",
    "user.email_confirmed",
    "user.login",
    "user.password_reset",
    "user.migrated",
  ],
  "CHECKOUT": [
    "checkout.started",
    "checkout.plus.started",
    "checkout.premium.started",
    "checkout.completed",
    "checkout.plus.completed",
    "checkout.premium.completed",
    "checkout.abandoned",
    "checkout.plus.abandoned",
    "checkout.premium.abandoned",
  ],
  "ASSINATURA": [
    "subscription.created",
    "subscription.renewed",
    "subscription.canceled",
    "subscription.payment_failed",
  ],
  "PLANO ATIVADO": [
    "plan.free_activated",
    "plan.plus_activated",
    "plan.premium_activated",
    "plan.ministry_activated",
  ],
  "UPGRADES ESPECÍFICOS": [
    "upgrade.free_to_plus",
    "upgrade.free_to_premium",
    "upgrade.plus_to_premium",
    "upgrade.plus_to_ministry",
    "upgrade.premium_to_ministry",
  ],
  "DOWNGRADES ESPECÍFICOS": [
    "downgrade.premium_to_plus",
    "downgrade.premium_to_free",
    "downgrade.plus_to_free",
    "downgrade.ministry_to_premium",
    "downgrade.ministry_to_plus",
    "downgrade.ministry_to_free",
  ],
  "PAGAMENTOS": [
    "payment.approved",
    "payment.refunded",
    "payment.chargeback",
  ],
  "MINISTERIAL": [
    "subscription.ministry_10.created",
    "subscription.ministry_20.created",
    "subscription.ministry_40.created",
    "subscription.ministry.canceled",
  ],
  "ENGAJAMENTO": [
    "repertoire.submitted",
    "repertoire.updated",
    "kit.downloaded",
    "playlist.created",
    "playlist.updated",
    "favorite.added",
  ],
} as const;

export const WEBHOOK_EVENT_LABELS: Record<string, string> = {
  "user.created": "Usuário criado",
  "user.email_confirmed": "E-mail confirmado",
  "user.login": "Login realizado",
  "user.password_reset": "Senha redefinida",
  "user.migrated": "Usuário migrado",

  "checkout.started": "Checkout iniciado",
  "checkout.plus.started": "Checkout Plus iniciado",
  "checkout.premium.started": "Checkout Premium iniciado",
  "checkout.completed": "Checkout concluído",
  "checkout.plus.completed": "Checkout Plus concluído",
  "checkout.premium.completed": "Checkout Premium concluído",
  "checkout.abandoned": "Checkout abandonado",
  "checkout.plus.abandoned": "Checkout Plus abandonado",
  "checkout.premium.abandoned": "Checkout Premium abandonado",

  "subscription.created": "Assinatura iniciada",
  "subscription.renewed": "Assinatura renovada",
  "subscription.canceled": "Assinatura cancelada",
  "subscription.payment_failed": "Falha de pagamento da assinatura",

  "subscription.free.created": "Free cadastrado",
  "subscription.plus.created": "Plus iniciado",
  "subscription.premium.created": "Premium iniciado",
  "subscription.ministry_10.created": "Ministerial 10 iniciado",
  "subscription.ministry_20.created": "Ministerial 20 iniciado",
  "subscription.ministry_40.created": "Ministerial 40 iniciado",
  "subscription.plus.canceled": "Plus cancelado",
  "subscription.premium.canceled": "Premium cancelado",
  "subscription.ministry.canceled": "Ministerial cancelado",

  "plan.free_activated": "Plano Free ativado",
  "plan.plus_activated": "Plano Plus ativado",
  "plan.premium_activated": "Plano Premium ativado",
  "plan.ministry_activated": "Plano Ministerial ativado",

  "upgrade.free_to_plus": "Upgrade: Free → Plus",
  "upgrade.free_to_premium": "Upgrade: Free → Premium",
  "upgrade.plus_to_premium": "Upgrade: Plus → Premium",
  "upgrade.plus_to_ministry": "Upgrade: Plus → Ministerial",
  "upgrade.premium_to_ministry": "Upgrade: Premium → Ministerial",

  "downgrade.premium_to_plus": "Downgrade: Premium → Plus",
  "downgrade.premium_to_free": "Downgrade: Premium → Free",
  "downgrade.plus_to_free": "Downgrade: Plus → Free",
  "downgrade.ministry_to_premium": "Downgrade: Ministerial → Premium",
  "downgrade.ministry_to_plus": "Downgrade: Ministerial → Plus",
  "downgrade.ministry_to_free": "Downgrade: Ministerial → Free",

  "payment.approved": "Pagamento aprovado",
  "payment.refunded": "Pagamento estornado",
  "payment.chargeback": "Pagamento contestado",

  "repertoire.submitted": "Repertório enviado",
  "repertoire.updated": "Repertório atualizado",
  "kit.downloaded": "Download de kit",
  "playlist.created": "Playlist criada",
  "playlist.updated": "Playlist atualizada",
  "favorite.added": "Favorito adicionado",
};

export const WEBHOOK_EVENTS = Object.values(WEBHOOK_EVENT_CATEGORIES).flat() as readonly string[];
export type WebhookEvent = (typeof WEBHOOK_EVENTS)[number];
