import { createHmac } from "crypto";
import { headers } from "next/headers";
import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { mapStripeStatus } from "@/lib/stripe/status";

export const runtime = "nodejs";
function verify(payload:string,sig:string,secret:string){const parts=Object.fromEntries(sig.split(',').map(p=>p.split('='))); const signed=`${parts.t}.${payload}`; const digest=createHmac('sha256',secret).update(signed,'utf8').digest('hex'); return digest===parts.v1;}
export async function POST(req: Request) { const sig=(await headers()).get('stripe-signature'); const secret=process.env.STRIPE_WEBHOOK_SECRET; if(!sig||!secret) return NextResponse.json({error:'missing signature'},{status:400}); const payload=await req.text(); if(!verify(payload,sig,secret)) return NextResponse.json({error:'invalid signature'},{status:400}); const event=JSON.parse(payload); const supabase=(await createClient()) as any; await supabase.from('billing_events').insert({provider:'stripe',event_type:event.type,payload:event,processed:false}); const obj=event.data?.object??{}; const stripeSubId=obj.id?.startsWith('sub_')?obj.id:obj.subscription; const status=mapStripeStatus(obj.status ?? (event.type==='invoice.payment_failed'?'past_due':'active')); if(stripeSubId){ await supabase.from('subscriptions').update({status,stripe_subscription_id:stripeSubId,stripe_customer_id:obj.customer,stripe_price_id:obj.items?.data?.[0]?.price?.id ?? obj.lines?.data?.[0]?.price?.id ?? null,current_period_end:obj.current_period_end?new Date(obj.current_period_end*1000).toISOString():null,next_billing_at:obj.current_period_end?new Date(obj.current_period_end*1000).toISOString():null,last_webhook_event:event.type,updated_at:new Date().toISOString()}).or(`stripe_subscription_id.eq.${stripeSubId},stripe_customer_id.eq.${obj.customer}`);} await supabase.from('billing_events').update({processed:true}).eq('provider','stripe').eq('event_type',event.type).order('created_at',{ascending:false}).limit(1); return NextResponse.json({received:true}); }
