"use client";

import {
  Check,
  ChevronDown,
  ChevronUp,
  Copy,
  CreditCard,
  Eye,
  EyeOff,
  MoreHorizontal,
  RefreshCw,
  Search,
  Shield,
  ShoppingCart,
  Sparkles,
  Users,
  Wallet,
  Webhook,
  X,
} from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { WEBHOOK_EVENT_CATEGORIES, WEBHOOK_EVENTS, WEBHOOK_PLANS, getWebhookEventLabel, type WebhookEndpoint } from "@/types/webhooks";

type FormState = { name: string; url: string; secret: string; environment: "production" | "test"; events: string[]; plans: string[]; retry_enabled: boolean; retry_attempts: number };
const baseForm: FormState = { name: "", url: "", secret: "", environment: "production", events: [...WEBHOOK_EVENTS], plans: [...WEBHOOK_PLANS], retry_enabled: true, retry_attempts: 3 };
const catIcons = { ASSINATURAS: CreditCard, CHECKOUT: ShoppingCart, PAGAMENTOS: Wallet, USUÁRIOS: Users, PLATAFORMA: Sparkles };

export function WebhookCenter() {
  const [endpoints, setEndpoints] = useState<WebhookEndpoint[]>([]); const [q, setQ] = useState(""); const [status, setStatus] = useState("all");
  const [loading, setLoading] = useState(true); const [drawerOpen, setDrawerOpen] = useState(false); const [form, setForm] = useState<FormState>(baseForm);
  const [secretVisible, setSecretVisible] = useState(false); const [openCats, setOpenCats] = useState<Record<string, boolean>>({ ASSINATURAS: true, CHECKOUT: true, PAGAMENTOS: true, USUÁRIOS: false, PLATAFORMA: false });

  async function loadEndpoints() { const res = await fetch("/api/admin/webhooks/endpoints"); const json = await res.json(); setEndpoints(json.data ?? []); setLoading(false); }
  useEffect(() => { void loadEndpoints(); }, []);

  const filtered = useMemo(() => endpoints.filter((e) => (status === "all" || (status === "active" ? e.active : !e.active)) && `${e.name} ${e.url} ${e.events.join(" ")} ${e.events.map(getWebhookEventLabel).join(" ")}`.toLowerCase().includes(q.toLowerCase())), [endpoints, q, status]);

  async function createEndpoint() { await fetch("/api/admin/webhooks/endpoints", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setDrawerOpen(false); setForm(baseForm); await loadEndpoints(); }
  async function toggleEndpoint(endpoint: WebhookEndpoint) { await fetch(`/api/admin/webhooks/endpoints/${endpoint.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !endpoint.active }) }); await loadEndpoints(); }
  async function regenerateSecret() { const res = await fetch("/api/admin/webhooks/endpoints/secret", { method: "POST" }); const j = await res.json(); setForm((f) => ({ ...f, secret: j.secret ?? "" })); }

  return <section className="space-y-5 text-zinc-100"><div className="rounded-3xl border border-white/10 bg-zinc-950/65 p-6 shadow-[0_0_40px_rgba(139,92,246,0.10)] backdrop-blur-xl"><div className="flex items-center justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight">Central de Webhooks</h1><p className="text-sm text-zinc-400">Operação premium com logs, testes e segurança HMAC SHA256.</p></div><button onClick={() => setDrawerOpen(true)} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-medium transition hover:bg-violet-500">Novo endpoint</button></div><div className="mt-5 grid gap-3 md:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><p className="text-xs uppercase text-zinc-500">Ativos</p><p className="mt-1 text-2xl font-semibold">{endpoints.filter((e) => e.active).length}</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><p className="text-xs uppercase text-zinc-500">Eventos configurados</p><p className="mt-1 text-2xl font-semibold">{endpoints.reduce((acc, e) => acc + e.events.length, 0)}</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><p className="text-xs uppercase text-zinc-500">Entregas recentes</p><p className="mt-1 text-2xl font-semibold">{endpoints.filter((e) => e.last_triggered_at).length}</p></div></div></div>

  <div className="rounded-2xl border border-white/10 bg-zinc-950/50 p-4 backdrop-blur-lg"><div className="mb-4 flex flex-wrap items-center gap-2"><div className="flex items-center gap-2 rounded-xl border border-zinc-700/70 bg-zinc-900/60 px-3 py-2"><Search size={16} /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Buscar por nome, URL ou evento" className="bg-transparent text-sm outline-none" /></div><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-xl border border-zinc-700/70 bg-zinc-900/70 px-3 py-2 text-sm"><option value="all">Todos</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select><Link href="/admin/webhooks/logs" className="rounded-xl border border-zinc-700/70 px-3 py-2 text-sm transition hover:bg-zinc-900/70">Logs premium</Link></div>
  <div className="overflow-auto"><table className="min-w-full text-sm"><thead className="text-left text-xs uppercase tracking-wide text-zinc-500"><tr><th className="pb-3">Endpoint</th><th className="pb-3">URL</th><th className="pb-3">Eventos</th><th className="pb-3">Status</th><th className="pb-3">Última entrega</th><th className="pb-3">Ações</th></tr></thead><tbody>{loading ? <tr><td colSpan={6} className="py-6">Carregando...</td></tr> : filtered.map((e) => <tr key={e.id} className="group border-t border-white/10 transition hover:bg-white/[0.03]"><td className="py-3"><p className="font-medium">{e.name}</p><p className="text-xs text-zinc-500">{e.environment === "production" ? "Produção" : "Teste"}</p></td><td className="max-w-xs truncate text-zinc-300">{e.url}</td><td><span className="rounded-full border border-cyan-400/30 bg-cyan-500/10 px-2.5 py-1 text-xs text-cyan-200">{e.events.length} selecionados</span></td><td><span className={`rounded-full px-2.5 py-1 text-xs ${e.active ? "border border-emerald-400/30 bg-emerald-500/10 text-emerald-200" : "border border-zinc-600 bg-zinc-800/80 text-zinc-300"}`}>{e.active ? "Ativo" : "Inativo"}</span></td><td className="text-zinc-400">{e.last_triggered_at ? new Date(e.last_triggered_at).toLocaleString("pt-BR") : "-"}</td><td><div className="flex gap-2 opacity-90"><Link href={`/admin/webhooks/${e.id}`} className="rounded-lg border border-zinc-700/80 px-2 py-1 text-xs hover:bg-zinc-800">Detalhes</Link><button onClick={() => toggleEndpoint(e)} className="rounded-lg border border-zinc-700/80 px-2 py-1 text-xs hover:bg-zinc-800">{e.active ? "Desativar" : "Ativar"}</button><button className="rounded-lg border border-zinc-700/80 px-2 py-1 hover:bg-zinc-800"><MoreHorizontal size={14} /></button></div></td></tr>)}</tbody></table></div></div>

  {drawerOpen && <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm"><aside className="absolute right-0 top-0 h-full w-full max-w-lg overflow-auto border-l border-white/10 bg-zinc-950/95 p-7 shadow-2xl"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-xl font-semibold">Novo endpoint</h2><p className="text-xs text-zinc-500">Configuração visual premium</p></div><button onClick={() => setDrawerOpen(false)} className="rounded-lg border border-zinc-700 p-2"><X size={16} /></button></div>
  <div className="space-y-5"><div className="space-y-3 rounded-2xl border border-white/10 bg-white/[0.02] p-4"><p className="text-xs uppercase tracking-wide text-zinc-500">Dados básicos</p><input className="w-full rounded-xl border border-zinc-700 bg-zinc-900/70 px-3 py-2 text-sm" placeholder="Nome do endpoint" value={form.name} onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))} /><input className="w-full rounded-xl border border-zinc-700 bg-zinc-900/70 px-3 py-2 text-sm" placeholder="URL de destino" value={form.url} onChange={(e) => setForm((f) => ({ ...f, url: e.target.value }))} /></div>
  <div className="space-y-3 rounded-2xl border border-white/10 bg-white/[0.02] p-4"><div className="flex items-center justify-between"><p className="text-xs uppercase tracking-wide text-zinc-500">Token de assinatura</p><Webhook size={14} className="text-violet-300" /></div><div className="flex gap-2"><input type={secretVisible ? "text" : "password"} className="flex-1 rounded-lg border border-zinc-700 bg-zinc-900 px-2 py-2 text-sm" value={form.secret} onChange={(e) => setForm((f) => ({ ...f, secret: e.target.value }))} /><button onClick={() => setSecretVisible((v) => !v)} className="rounded-lg border border-zinc-700 px-3">{secretVisible ? <EyeOff size={14} /> : <Eye size={14} />}</button><button onClick={() => navigator.clipboard.writeText(form.secret)} className="rounded-lg border border-zinc-700 px-3"><Copy size={14} /></button><button onClick={regenerateSecret} className="rounded-lg border border-zinc-700 px-3"><RefreshCw size={14} /></button></div><p className="text-xs text-zinc-500">Utilize esta chave para validar a autenticidade dos eventos enviados.</p></div>
  <div className="space-y-3 rounded-2xl border border-white/10 bg-white/[0.02] p-4"><div className="mb-1 flex items-center justify-between"><p className="text-xs uppercase tracking-wide text-zinc-500">Eventos</p><button onClick={() => setForm((f) => ({ ...f, events: [...WEBHOOK_EVENTS] }))} className="text-xs text-cyan-300 hover:text-cyan-200">Selecionar todos</button></div>{Object.entries(WEBHOOK_EVENT_CATEGORIES).map(([cat, events]) => { const Icon = catIcons[cat as keyof typeof catIcons]; const isOpen = openCats[cat] ?? false; return <div key={cat} className="rounded-xl border border-white/10 bg-zinc-900/30"><button onClick={() => setOpenCats((s) => ({ ...s, [cat]: !isOpen }))} className="flex w-full items-center justify-between px-3 py-2"><div className="flex items-center gap-2 text-sm font-medium"><Icon size={14} className="text-violet-300" />{cat}</div>{isOpen ? <ChevronUp size={14} /> : <ChevronDown size={14} />}</button>{isOpen && <div className="flex flex-wrap gap-2 px-3 pb-3">{events.map((ev) => { const active = form.events.includes(ev); return <button key={ev} onClick={() => setForm((f) => ({ ...f, events: active ? f.events.filter((x) => x !== ev) : [...f.events, ev] }))} className={`rounded-full border px-3 py-1.5 text-xs transition ${active ? "border-emerald-400/40 bg-emerald-500/15 text-emerald-200" : "border-zinc-700 bg-zinc-900/70 text-zinc-300 hover:border-zinc-500"}`}>{active ? <span className="mr-1 inline-flex"><Check size={12} /></span> : null}{getWebhookEventLabel(ev)}</button>; })}</div>}</div>; })}</div>
  <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><p className="mb-2 text-xs uppercase tracking-wide text-zinc-500">Planos</p><div className="flex flex-wrap gap-2">{WEBHOOK_PLANS.map((p) => { const active = form.plans.includes(p); return <button key={p} onClick={() => setForm((f) => ({ ...f, plans: active ? f.plans.filter((x) => x !== p) : [...f.plans, p] }))} className={`rounded-full border px-3 py-1.5 text-xs uppercase ${active ? "border-violet-400/40 bg-violet-500/15 text-violet-200" : "border-zinc-700 bg-zinc-900/70 text-zinc-300"}`}>{p}</button>; })}</div></div>
  <button onClick={createEndpoint} className="w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold transition hover:bg-violet-500">Salvar endpoint</button>
  <p className="flex items-center gap-2 text-xs text-zinc-500"><Shield size={14} /> Assinatura mantida: X-Harmomus-Signature / Event / Delivery.</p></div></aside></div>}
  </section>;
}
