"use client";
import { Check, Copy, MoreHorizontal, RefreshCw, Search, Shield, Webhook, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { WEBHOOK_EVENT_CATEGORIES, WEBHOOK_EVENTS, WEBHOOK_PLANS, type WebhookEndpoint } from "@/types/webhooks";

type FormState = { name: string; url: string; secret: string; environment: "production" | "test"; events: string[]; plans: string[]; retry_enabled: boolean; retry_attempts: number };
const baseForm: FormState = { name: "", url: "", secret: "", environment: "production", events: [...WEBHOOK_EVENTS], plans: [...WEBHOOK_PLANS], retry_enabled: true, retry_attempts: 3 };

export function WebhookCenter() {
  const [endpoints, setEndpoints] = useState<WebhookEndpoint[]>([]); const [q, setQ] = useState(""); const [status, setStatus] = useState("all");
  const [loading, setLoading] = useState(true); const [drawerOpen, setDrawerOpen] = useState(false); const [form, setForm] = useState<FormState>(baseForm);

  async function loadEndpoints() { const res = await fetch("/api/admin/webhooks/endpoints"); const json = await res.json(); setEndpoints(json.data ?? []); setLoading(false); }
  useEffect(() => { void loadEndpoints(); }, []);

  const filtered = useMemo(() => endpoints.filter((e) => (status === "all" || (status === "active" ? e.active : !e.active)) && `${e.name} ${e.url} ${e.events.join(" ")}`.toLowerCase().includes(q.toLowerCase())), [endpoints, q, status]);

  async function createEndpoint() { await fetch("/api/admin/webhooks/endpoints", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setDrawerOpen(false); setForm(baseForm); await loadEndpoints(); }
  async function toggleEndpoint(endpoint: WebhookEndpoint) { await fetch(`/api/admin/webhooks/endpoints/${endpoint.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !endpoint.active }) }); await loadEndpoints(); }
  async function regenerateSecret() { const res = await fetch("/api/admin/webhooks/endpoints/secret", { method: "POST" }); const j = await res.json(); setForm((f) => ({ ...f, secret: j.secret ?? "" })); }

  return <section className="space-y-5 text-zinc-100"><div className="rounded-3xl border border-violet-500/30 bg-zinc-950/70 p-6 shadow-2xl backdrop-blur"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold">Central de Webhooks</h1><p className="text-zinc-400">Operação premium com logs, testes e segurança HMAC SHA256.</p></div><button onClick={() => setDrawerOpen(true)} className="rounded-xl bg-violet-600 px-4 py-2">Novo Endpoint</button></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-zinc-900/70 p-3">Ativos: {endpoints.filter((e) => e.active).length}</div><div className="rounded-xl bg-zinc-900/70 p-3">Eventos ativos: {endpoints.reduce((acc, e) => acc + e.events.length, 0)}</div><div className="rounded-xl bg-zinc-900/70 p-3">Últimas entregas: {endpoints.filter((e) => e.last_triggered_at).length}</div></div></div>

  <div className="rounded-2xl border border-zinc-800 bg-zinc-950/50 p-4"><div className="mb-4 flex flex-wrap items-center gap-2"><div className="flex items-center gap-2 rounded-xl border border-zinc-700 px-3 py-2"><Search size={16} /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Buscar por nome, URL, eventos" className="bg-transparent outline-none" /></div><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-xl border border-zinc-700 bg-zinc-900 px-3 py-2"><option value="all">Todos</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select><Link href="/admin/webhooks/logs" className="rounded-xl border border-zinc-700 px-3 py-2">Logs premium</Link></div>
  <div className="overflow-auto"><table className="min-w-full text-sm"><thead className="text-left text-zinc-400"><tr><th>Nome</th><th>URL</th><th>Eventos ativos</th><th>Status</th><th>Última entrega</th><th>Sucesso/Falha</th><th></th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className="py-6">Carregando...</td></tr> : filtered.map((e) => <tr key={e.id} className="border-t border-zinc-800"><td className="py-3 font-medium">{e.name}</td><td>{e.url}</td><td><span className="rounded-full bg-cyan-500/20 px-2 py-1 text-cyan-300">{e.events.length} eventos</span></td><td><span className={`rounded-full px-2 py-1 ${e.active ? "bg-emerald-500/20 text-emerald-300" : "bg-zinc-700 text-zinc-300"}`}>{e.active ? "Ativo" : "Inativo"}</span></td><td>{e.last_triggered_at ? new Date(e.last_triggered_at).toLocaleString("pt-BR") : "-"}</td><td><span className="rounded-full bg-violet-500/20 px-2 py-1">N/A</span></td><td><div className="flex gap-2"><Link href={`/admin/webhooks/${e.id}`} className="rounded-lg border border-zinc-700 px-2 py-1">Detalhes</Link><button onClick={() => toggleEndpoint(e)} className="rounded-lg border border-zinc-700 px-2 py-1">{e.active ? "Desativar" : "Ativar"}</button><button className="rounded-lg border border-zinc-700 px-2 py-1"><MoreHorizontal size={14} /></button></div></td></tr>)}</tbody></table></div></div>

  {drawerOpen && <div className="fixed inset-0 z-50 bg-black/70"><aside className="absolute right-0 top-0 h-full w-full max-w-xl overflow-auto border-l border-zinc-800 bg-zinc-950 p-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-semibold">Criar/Editar endpoint</h2><button onClick={() => setDrawerOpen(false)}><X /></button></div>
  <div className="space-y-3"><input className="w-full rounded-xl border border-zinc-700 bg-zinc-900 px-3 py-2" placeholder="Nome" value={form.name} onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))} /><input className="w-full rounded-xl border border-zinc-700 bg-zinc-900 px-3 py-2" placeholder="URL" value={form.url} onChange={(e) => setForm((f) => ({ ...f, url: e.target.value }))} />
  <div className="rounded-xl border border-zinc-700 p-3"><p className="mb-2 text-sm text-zinc-400">Secret / token</p><div className="flex gap-2"><input className="flex-1 rounded-lg border border-zinc-700 bg-zinc-900 px-2 py-2" value={form.secret} onChange={(e) => setForm((f) => ({ ...f, secret: e.target.value }))} /><button onClick={() => navigator.clipboard.writeText(form.secret)} className="rounded-lg border border-zinc-700 px-3"><Copy size={14} /></button><button onClick={regenerateSecret} className="rounded-lg border border-zinc-700 px-3"><RefreshCw size={14} /></button></div></div>
  <div className="rounded-xl border border-zinc-700 p-3"><div className="mb-2 flex items-center justify-between"><p className="text-sm text-zinc-400">Eventos</p><button onClick={() => setForm((f) => ({ ...f, events: [...WEBHOOK_EVENTS] }))} className="text-xs text-cyan-300">Selecionar todos</button></div>{Object.entries(WEBHOOK_EVENT_CATEGORIES).map(([cat, events]) => <div key={cat} className="mb-2"><p className="mb-1 text-xs text-zinc-500">{cat}</p><div className="grid grid-cols-1 gap-1">{events.map((ev) => <label key={ev} className="text-sm"><input type="checkbox" checked={form.events.includes(ev)} onChange={() => setForm((f) => ({ ...f, events: f.events.includes(ev) ? f.events.filter((x) => x !== ev) : [...f.events, ev] }))} /> {ev}</label>)}</div></div>)}</div>
  <div className="rounded-xl border border-zinc-700 p-3"><p className="mb-2 text-sm text-zinc-400">Planos</p><label className="mr-3"><input type="checkbox" checked={form.plans.length === WEBHOOK_PLANS.length} onChange={() => setForm((f) => ({ ...f, plans: f.plans.length === WEBHOOK_PLANS.length ? [] : [...WEBHOOK_PLANS] }))} /> todos os planos</label>{WEBHOOK_PLANS.map((p) => <label key={p} className="mr-3"><input type="checkbox" checked={form.plans.includes(p)} onChange={() => setForm((f) => ({ ...f, plans: f.plans.includes(p) ? f.plans.filter((x) => x !== p) : [...f.plans, p] }))} /> {p}</label>)}</div>
  <button onClick={createEndpoint} className="w-full rounded-xl bg-violet-600 px-4 py-3 font-semibold">Salvar endpoint</button>
  <p className="flex items-center gap-2 text-xs text-zinc-500"><Shield size={14} /> Assinatura mantida: X-Harmomus-Signature / Event / Delivery.</p></div></aside></div>}
  </section>;
}
