-- Starter templates for behavior-based marketing automations.
-- All automations are seeded as draft by default. Review inside Admin > Comunicação > Automações, then set status='active'.

insert into public.marketing_automations (
  name,
  description,
  trigger_event,
  intent,
  priority,
  score_weight,
  score_threshold,
  lookback_hours,
  cooldown_hours,
  channel,
  status,
  message_template,
  cta_url,
  audience_rule,
  metadata
)
values
  (
    'Upgrade: recurso Premium bloqueado',
    'Usuário Free/Plus tentou usar recursos Premium várias vezes na semana. Oferta direta para upgrade.',
    'premium_blocked',
    'upgrade_premium',
    30,
    3,
    8,
    168,
    168,
    'whatsapp',
    'draft',
    'Oi, {{nome}}! Vi que você tentou acessar alguns recursos Premium no Harmomus e eles ainda estão bloqueados no seu plano.\n\nCom o Premium você libera todos os kits, tons e recursos para estudar sem travar no meio do ensaio.\n\nPara desbloquear hoje, acesse: {{link}}',
    '/assinar?plano=premium&utm_source=crm&utm_medium=whatsapp&utm_campaign=premium_blocked',
    '{"plans":["free","plus"],"min_blocks":3}'::jsonb,
    '{"category":"upgrade","temperature":"hot","recommended_delay_minutes":30}'::jsonb
  ),
  (
    'Upgrade: troca de tom bloqueada',
    'Usuário tentou acessar tons bloqueados, sinal claro de dor ligada ao estudo vocal.',
    'tone_blocked',
    'upgrade_tones',
    35,
    3,
    6,
    168,
    168,
    'whatsapp',
    'draft',
    'Oi, {{nome}}! Percebi que você tentou acessar outro tom em um kit do Harmomus.\n\nEsse recurso faz muita diferença quando a música não está confortável para sua voz ou para o grupo.\n\nVocê pode liberar os tons disponíveis fazendo upgrade aqui: {{link}}',
    '/assinar?utm_source=crm&utm_medium=whatsapp&utm_campaign=tone_blocked',
    '{"plans":["free","plus"],"min_blocks":2}'::jsonb,
    '{"category":"upgrade","temperature":"hot","recommended_delay_minutes":45}'::jsonb
  ),
  (
    'Recuperação: checkout abandonado',
    'Usuário iniciou checkout, mas não concluiu dentro da janela definida.',
    'checkout_started',
    'checkout_abandoned',
    20,
    10,
    10,
    48,
    48,
    'whatsapp',
    'draft',
    '{{nome}}, você estava a um passo de liberar os recursos pagos do Harmomus.\n\nSeu acesso ainda não foi ativado porque o checkout não foi finalizado.\n\nFinalize por aqui e volte a estudar com tudo liberado: {{link}}',
    '/assinar?utm_source=crm&utm_medium=whatsapp&utm_campaign=checkout_abandoned',
    '{"exclude_events":["checkout_completed","subscription_created","invoice.paid"],"window_hours":24}'::jsonb,
    '{"category":"recovery","temperature":"very_hot","recommended_delay_minutes":60}'::jsonb
  ),
  (
    'Recuperação: pagamento falhou',
    'Usuário com tentativa de pagamento falha ou assinatura em risco.',
    'payment_failed',
    'payment_recovery',
    10,
    15,
    15,
    72,
    48,
    'whatsapp',
    'draft',
    'Oi, {{nome}}! Seu pagamento do Harmomus não foi confirmado.\n\nPara evitar bloqueio no acesso aos kits e recursos, regularize sua assinatura por aqui: {{link}}',
    '/conta/assinatura?utm_source=crm&utm_medium=whatsapp&utm_campaign=payment_failed',
    '{"statuses":["past_due","payment_failed","open"]}'::jsonb,
    '{"category":"billing","temperature":"urgent","recommended_delay_minutes":15}'::jsonb
  ),
  (
    'Ativação: Free engajado',
    'Usuário Free consumiu bastante conteúdo na semana e pode estar pronto para upgrade.',
    'audio_played',
    'free_active_upgrade',
    60,
    2,
    8,
    168,
    120,
    'whatsapp',
    'draft',
    'Oi, {{nome}}! Vi que você já está usando o Harmomus nos seus estudos.\n\nCom o upgrade, você libera mais kits, tons e recursos para estudar com mais liberdade e praticidade.\n\nVeja os planos aqui: {{link}}',
    '/assinar?utm_source=crm&utm_medium=whatsapp&utm_campaign=free_active',
    '{"plans":["free"],"min_plays":4}'::jsonb,
    '{"category":"activation","temperature":"warm","recommended_delay_minutes":180}'::jsonb
  ),
  (
    'Expansão: Plus para Premium',
    'Assinante Plus com consumo relevante recebe convite para liberar experiência completa.',
    'audio_played',
    'plus_to_premium',
    50,
    2,
    10,
    168,
    168,
    'whatsapp',
    'draft',
    'Oi, {{nome}}! Você já está usando bastante o Harmomus no Plus.\n\nO Premium libera a experiência completa: mais kits, mais possibilidades e recursos avançados para seu estudo vocal.\n\nFaça o upgrade aqui: {{link}}',
    '/assinar?plano=premium&utm_source=crm&utm_medium=whatsapp&utm_campaign=plus_to_premium',
    '{"plans":["plus"],"min_plays":5}'::jsonb,
    '{"category":"expansion","temperature":"warm","recommended_delay_minutes":240}'::jsonb
  ),
  (
    'Reativação: usuário sem uso recente',
    'Modelo preparado para reativar usuários que ficaram sem acessar. Depende do evento/login ou rotina futura de inatividade.',
    'inactive_user',
    'reactivation',
    90,
    5,
    5,
    720,
    360,
    'whatsapp',
    'draft',
    'Oi, {{nome}}! Passando para te lembrar que o Harmomus pode te ajudar nos estudos da semana.\n\nTem kits e recursos esperando por você na plataforma.\n\nAcesse aqui: {{link}}',
    '/?utm_source=crm&utm_medium=whatsapp&utm_campaign=inactive_user',
    '{"min_inactive_days":14}'::jsonb,
    '{"category":"reactivation","temperature":"cold","recommended_delay_minutes":0}'::jsonb
  ),
  (
    'Onboarding: novo usuário Free',
    'Mensagem de boas-vindas para orientar novo cadastro a usar melhor o Harmomus. Depende do evento signup_completed.',
    'signup_completed',
    'onboarding_free',
    100,
    5,
    5,
    24,
    168,
    'whatsapp',
    'draft',
    'Oi, {{nome}}! Seja bem-vindo ao Harmomus. 🙌\n\nComece explorando os kits disponíveis e salve seus favoritos para estudar com mais facilidade.\n\nAcesse aqui: {{link}}',
    '/?utm_source=crm&utm_medium=whatsapp&utm_campaign=onboarding_free',
    '{"plans":["free"]}'::jsonb,
    '{"category":"onboarding","temperature":"new","recommended_delay_minutes":10}'::jsonb
  ),
  (
    'Oferta: lead muito quente',
    'Usuário acumula múltiplos sinais de intenção. Pode ser usado para campanha mais forte ou atendimento manual.',
    'checkout_started',
    'very_hot_offer',
    15,
    12,
    20,
    168,
    72,
    'whatsapp',
    'draft',
    '{{nome}}, percebi que você demonstrou bastante interesse em liberar os recursos do Harmomus.\n\nSe sua intenção é estudar com mais praticidade, esse é o melhor próximo passo.\n\nFinalize seu acesso aqui: {{link}}',
    '/assinar?utm_source=crm&utm_medium=whatsapp&utm_campaign=very_hot_offer',
    '{"exclude_events":["checkout_completed","subscription_created","invoice.paid"],"window_hours":72}'::jsonb,
    '{"category":"offer","temperature":"very_hot","recommended_delay_minutes":120}'::jsonb
  ),
  (
    'Relacionamento: uso recorrente sem upgrade',
    'Usuário Free usa com frequência, mas ainda não tentou checkout. Mensagem consultiva, sem pressão.',
    'audio_played',
    'nurture_free_user',
    80,
    1,
    12,
    168,
    240,
    'whatsapp',
    'draft',
    'Oi, {{nome}}! Que bom ver você usando o Harmomus com frequência.\n\nSe quiser acelerar seus estudos, os planos pagos liberam mais recursos e dão mais liberdade para ensaiar.\n\nVeja aqui: {{link}}',
    '/assinar?utm_source=crm&utm_medium=whatsapp&utm_campaign=nurture_free_user',
    '{"plans":["free"],"min_plays":8}'::jsonb,
    '{"category":"nurture","temperature":"warm","recommended_delay_minutes":360}'::jsonb
  )
on conflict do nothing;

-- Ensure the original starter automations receive stronger, production-ready copies only if they were not already manually customized.
-- To activate after review:
-- update public.marketing_automations set status='active' where name in (...desired automation names...);
